# Generated by Django 4.1.3 on 2023-05-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypurchasetotal',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
