# Generated by Django 4.1.3 on 2023-04-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "procurement",
            "0002_remove_purchase_supplier_purchasedproduct_supplier_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasedproduct",
            name="date",
        ),
    ]
