# Generated by Django 4.1.3 on 2023-04-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_remove_purchasedproduct_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasedproduct",
            name="supplier",
        ),
        migrations.AddField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier",
                to="procurement.supplier",
            ),
        ),
    ]
