# Generated by Django 4.1.3 on 2023-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_remove_purchasedproduct_supplier_purchase_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="total_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
