# Generated by Django 4.1.3 on 2023-04-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['date']},
        ),
    ]
