# Generated by Django 4.1.3 on 2023-04-03 16:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_dailysales_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number'),
        ),
    ]
