# Generated by Django 4.1.3 on 2023-01-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tona_users', '0002_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
