# Generated by Django 4.1.3 on 2022-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tona_users', '0002_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Sales'), (2, 'Delivery')], null=True),
        ),
    ]
