# Generated by Django 4.1.3 on 2023-01-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tona_users', '0003_alter_useractivity_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='query_params',
            new_name='user_group',
        ),
    ]
