# Generated by Django 4.1.3 on 2023-01-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_supplier_email_remove_supplier_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="associatedcost",
            old_name="cost_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="associatedcost",
            old_name="cost_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="purchase_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="purchasedproduct",
            old_name="purchase_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="purchasedproduct",
            old_name="purchase_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="sale_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="soldproduct",
            old_name="sale_date",
            new_name="date",
        ),
    ]
