# Generated by Django 4.1.3 on 2023-03-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_soldproduct_unit_price_alter_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.customer'),
        ),
    ]
