# Generated by Django 4.1.3 on 2023-03-23 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_soldproduct_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_products',
            field=models.ManyToManyField(related_name='sales', to='store.soldproduct'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
