# Generated by Django 4.1.3 on 2023-03-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_sale_total_income_alter_sale_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchased_products',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssociatedCost',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchasedProduct',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
